// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QueryGitLogs(arg1) {
  return window['go']['main']['App']['QueryGitLogs'](arg1);
}

export function ScanRepositories(arg1) {
  return window['go']['main']['App']['ScanRepositories'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
