// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function QueryGitLogs(arg1:model.GitLogRequest):Promise<model.GitLogResponse>;

export function ScanRepositories(arg1:model.ScanRequest):Promise<Array<model.RepoInfo>>;

export function SelectDirectory():Promise<string>;
